# NumPy

## 1、NumPy ndarray：多维数组对象

In [1]:
import numpy as np
data=np.random.randn(2,3)
print(data,data.shape,data.dtype,sep='\n')

#numpy库引入了数组类型，可以方便地进行矩阵运算
#数组内默认数据类型为float64

[[ 2.2538779   1.97717457 -1.45390912]
 [ 1.39385683  0.18391206 -0.55957088]]
(2, 3)
float64


### 1.1生成ndarray

In [15]:
data1=[1,2,3,3.5]
array1=np.array(data1)
data2=[[1,2,3,3.5],[2,3,4,4.5]]
array2=np.array(data2)
print(array1,array2,type(array2),array2.ndim,array2.shape,sep='\n')   #ndarray的nidm方法返回当前数组的维度，shape返回具体的维度大小

arr3=np.empty((2,3,3))   #返回指定大小的未初始化垃圾数据
arr4=np.zeros((3,5))
print('\n',arr3,arr4,sep='\n')

arr5=np.arange(10)       #arange为数组版的range，返回一个数组的序列
print('\n',arr5,sep='\n')

[1.  2.  3.  3.5]
[[1.  2.  3.  3.5]
 [2.  3.  4.  4.5]]
<class 'numpy.ndarray'>
2
(2, 4)


[[[6.23042070e-307 7.56587584e-307 1.37961302e-306]
  [6.23053614e-307 6.23053954e-307 9.34609790e-307]
  [8.45593934e-307 9.34600963e-307 1.86921143e-306]]

 [[6.23061763e-307 8.90104239e-307 6.89804132e-307]
  [1.22387805e-307 1.42418172e-306 8.06610070e-308]
  [6.89810244e-307 1.22387550e-307 2.22522596e-306]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0 1 2 3 4 5 6 7 8 9]


### 1.2、ndarray的数据类型

In [21]:
arr1=np.array([1.5,2.89,-3.15,4.0],dtype=np.float64)   #直接设定内部的数据类型
print(arr1.dtype)
int_arr1=arr1.astype(np.int64)           #利用astype可以改变数据类型
print(int_arr1.dtype)
print(arr1,int_arr1,sep='\n')           #浮点数转换为整形数之后，小数部分消失

arr2=np.array(['1.25','5.55','6.78'])
float_arr2=arr2.astype(np.float64)     #还可以将具有数字含义的字符串转换为数字
#float_arr2=arr2.astype(arr1.dtype)   同样可以
print(arr2,float_arr2,sep='\n')

float64
int64
[ 1.5   2.89 -3.15  4.  ]
[ 1  2 -3  4]
['1.25' '5.55' '6.78']
[1.25 5.55 6.78]


### 1.3、NumPy数组算术

In [25]:
#任何两个等尺寸数组之间的算术操作都是对应元素的
arr1=np.array([[1,2,3],[2,3,4]])
print(arr1,arr1+arr1,arr1*arr1,1/arr1,arr1**2,sep='\n')
arr2=np.array([[2,3,4],[4,5,6]])
print(arr1>arr2)

[[1 2 3]
 [2 3 4]]
[[2 4 6]
 [4 6 8]]
[[ 1  4  9]
 [ 4  9 16]]
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]]
[[ 1  4  9]
 [ 4  9 16]]
[[False False False]
 [False False False]]


### 1.4、索引与切片

In [41]:
arr1=np.arange(10)
print(arr1)
arr1[5:8]=12
print(arr1)

#比较独特的是数组的切片就是原数组的视图，对切片的修改会传递到原数组上
slice_arr1=arr1[5:8]     #slice_arr1类似指向了arr1的该部分，而不是复制
#copy_arr1=arr1[5:8].copy()   这是复制
slice_arr1[:]=20
print(arr1,slice_arr1)

print('\n')
#与之相对的是列表，自动复制
list1=[2,3,4,5]
list1[1:3]=[12,12]
print(list1)
mp=list1[1:3]
mp=[22,22]
print(list1)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 20 20 20  8  9] [20 20 20]


[2, 12, 12, 5]
[2, 12, 12, 5]


In [44]:
#多维数组中的索引
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0,2],arr2[0][2],sep='\n')   #两种效果相同
print(arr2[1])

arr3=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
print('\n',arr3[1],arr3[0,1],arr3[0,:1,1:],sep='\n')    #切片时是一步步进行的

3
3
[4 5 6]


[[2 3 4]
 [5 6 7]]
[4 5 6]
[[2 3]]


### 1.5、布尔索引

In [17]:
import numpy as np
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(data,'\n')
print(names=='Bob','\n')
print(data[names=='Bob'],'\n')      #names=='Bob'会产生布尔值数组，因此可以借此作为索引
print(data[names!='Bob'],'\n')
print(data[~(names=='Bob')])

[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  2.06353861]] 

[ True False False  True False False False] 

[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]] 

[[-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  2.06353861]] 

[[-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -

In [21]:
#注意用布尔值索引，产生的不是原本数据的视图，而是拷贝
slice_bool_data=data[names=='Bob']
slice_data=data[[0,3],:]
print(slice_bool_data,slice_data,sep='\n')
slice_bool_data[:,:]=1
print('利用bool索引的数据是拷贝',slice_bool_data,data,sep='\n')
slice_data[:,:]=1
print('利用数组分隔选取的也是拷贝',slice_data,data,sep='\n')


[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]]
[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]]
利用bool索引的数据是拷贝
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  2.06353861]]
利用数组分隔选取的也是拷贝
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  

In [22]:
data[data<0]=0  #这个也是布尔值索引
print(data)

[[0.         0.         0.         0.        ]
 [0.         3.28875937 0.         0.        ]
 [0.59065563 0.11076274 0.         0.        ]
 [0.         0.82945829 0.         0.        ]
 [0.         0.9233171  0.311079   0.35140152]
 [0.19176876 1.21821396 0.60720216 1.31797562]
 [1.32861849 0.         0.         2.06353861]]


### 1.6、神奇索引

In [31]:
arr=np.empty((8,4))
for i in range(8):
    arr[i,:]=i
print(arr,end='\n\n')
print(arr[[3,5,4,1],:],'\n',sep='\n')        #神奇索引就是用整数数组进行索引。可以发现，顺序也是可以调换的
print(arr[[-3,-7,-2,-1,0],:],'\n',sep='\n')        #负数就是倒着索引
print(arr[[1,3,5,2],[3,2,0,1]])           #会选取两个数组组合所指向的元素
                                           #会总是将数据复制到一个新数组中

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

[[3. 3. 3. 3.]
 [5. 5. 5. 5.]
 [4. 4. 4. 4.]
 [1. 1. 1. 1.]]


[[5. 5. 5. 5.]
 [1. 1. 1. 1.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]
 [0. 0. 0. 0.]]


[1. 3. 5. 2.]


In [33]:
arr=np.arange(32).reshape((8,4))
print(arr,'\n',arr[[1,5,7,2]][:,[0,3,2,1]],sep='\n')        #arr[[1,5,7,2]]是选中的行，接着选取[:,[0,3,2,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  7  6  5]
 [20 23 22 21]
 [28 31 30 29]
 [ 8 11 10  9]]


### 1.7、数组转置、换轴

In [34]:
#数组的转置
print(arr.T)

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [36]:
#矩阵乘
print(np.dot(arr.T,arr))
print(np.dot(arr,arr.T))

[[2240 2352 2464 2576]
 [2352 2472 2592 2712]
 [2464 2592 2720 2848]
 [2576 2712 2848 2984]]
[[  14   38   62   86  110  134  158  182]
 [  38  126  214  302  390  478  566  654]
 [  62  214  366  518  670  822  974 1126]
 [  86  302  518  734  950 1166 1382 1598]
 [ 110  390  670  950 1230 1510 1790 2070]
 [ 134  478  822 1166 1510 1854 2198 2542]
 [ 158  566  974 1382 1790 2198 2606 3014]
 [ 182  654 1126 1598 2070 2542 3014 3486]]


In [47]:
#数组的高维转置
arr=np.arange(16).reshape((2,2,4))
print(arr)
arr_trans=arr.transpose((1,0,2))   #即旧的第二个轴变成了第一个，第一个轴变成了第二个，第三个轴不变，1，0，2分别代表旧数组的第二、一、三个轴
print('.....',arr_trans.shape)
arr_trans=arr.transpose((2,1,0))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((2,0,1))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((1,2,0))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((0,1,2))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((0,2,1))
print('.....',arr_trans.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
..... (2, 2, 4)
..... (4, 2, 2)
..... (4, 2, 2)
..... (2, 4, 2)
..... (2, 2, 4)
..... (2, 4, 2)


In [48]:
#swapaxes方法
arr.swapaxes(1,2)      #接收一对轴编号，对这两个轴进行调换。注意，返回的是视图

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 2、通用函数

In [50]:
#通用函数，称ufunc，是对ndarry数据逐元素操作的函数。

arr=np.arange(16).reshape(2,8)
print(np.sqrt(arr),'\n')
print(np.exp(arr))

[[0.         1.         1.41421356 1.73205081 2.         2.23606798
  2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128
  3.74165739 3.87298335]] 

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
  1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]]


In [52]:
#modf返回浮点数的小数和整数部分
arr=np.random.randn(7)
remainder,whole_part=np.modf(arr)
print(arr,remainder,whole_part,sep='\n')

[ 2.20828071 -1.67689482 -1.12481404  1.64234093 -0.25654576  1.06180184
  0.78453939]
[ 0.20828071 -0.67689482 -0.12481404  0.64234093 -0.25654576  0.06180184
  0.78453939]
[ 2. -1. -1.  1. -0.  1.  0.]


In [60]:
arr=np.arange(16).reshape(2,8)
arr=arr.astype(np.float64)
arr1=np.sqrt(arr)
print(arr,'\n')
arr2=np.empty((2,8))
arr1=np.sqrt(arr,arr2)
print(arr,arr2,sep='\n')        #ufunc提供一个out参数，可以将计算结果输出到out中

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]] 

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]]
[[0.         1.         1.41421356 1.73205081 2.         2.23606798
  2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128
  3.74165739 3.87298335]]


## 3、面向数组编程

In [1]:
#即为利用数组进行大量数据操作，而无需大量的循环
#numpy数组的向量操作比python操作快得多，数据越多，快的更明显

### 3.1、条件逻辑

In [3]:
#np.where()函数。利用逻辑向量来选取向量元素
import numpy as np
#example1
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
result=np.where(cond,xarr,yarr)        #实现的功能：cond中的元素为True时，选取xarr中的元素，否则选取yarr中的
print(result)                          #同时后面的xarr、yarr位置也可以是标量

  #与之相对的是传统方法
result_old=[(x if c else y) for x,c,y in zip(xarr,cond,yarr)]
print(result_old)

[1.1 2.2 1.3 1.4 2.5]
[1.1, 2.2, 1.3, 1.4, 2.5]


### 3.2、数学与统计方法

In [7]:
#如sum、mean、std(标准差)等称为聚合函数，既可以调用数组实例的方法，也可以用顶层函数
arr=np.random.randn(5,4)
print(arr.mean(),np.mean(arr),arr.sum())         #聚合函数求的均为全部元素的
print(arr.mean(axis=0))                   #求沿着轴0进行求平均数，即每列的平均值
print(arr.mean(1))

0.03367581267165992 0.03367581267165992 0.6735162534331984
[-0.25356245  0.13613466 -0.39818067  0.65031172]
[ 0.3051927   0.07338224 -0.10636532 -0.05859867 -0.04523189]


### 3.3、布尔值数组的方法

In [13]:
#sum可以计算布尔数组中true的个数
arr=np.random.randn(100)
print(np.sum((arr>=0)))

#any、all检查布尔数组中是否有一个true，和是否全是true
print((arr>0).any())
print((arr>0).all())

46
True
False


### 3.4、排序

In [15]:
#顶层与数组实例均拥有一个sort方法，顶层返回一个排序后的复制，而数组实例对原数组进行排序变换
arr=np.random.randn(5,4)
print(arr)
arr1=np.sort(arr)
print(arr)
arr.sort()
print(arr)

#sort中也可以传递axis值
arr.sort(0)        #沿着0轴进行排序
print(arr)

[[ 1.94582503  0.11319779  0.1188488  -0.89788122]
 [ 0.17000839  0.42312224  1.20535205 -0.75857622]
 [-0.4389906   1.13049576  1.47334803 -1.56675547]
 [-0.62665751  1.51688198  0.30333591  1.21490304]
 [-0.87112033  0.47086861 -0.56550695 -0.28485136]]
[[ 1.94582503  0.11319779  0.1188488  -0.89788122]
 [ 0.17000839  0.42312224  1.20535205 -0.75857622]
 [-0.4389906   1.13049576  1.47334803 -1.56675547]
 [-0.62665751  1.51688198  0.30333591  1.21490304]
 [-0.87112033  0.47086861 -0.56550695 -0.28485136]]
[[-0.89788122  0.11319779  0.1188488   1.94582503]
 [-0.75857622  0.17000839  0.42312224  1.20535205]
 [-1.56675547 -0.4389906   1.13049576  1.47334803]
 [-0.62665751  0.30333591  1.21490304  1.51688198]
 [-0.87112033 -0.56550695 -0.28485136  0.47086861]]
[[-1.56675547 -0.56550695 -0.28485136  0.47086861]
 [-0.89788122 -0.4389906   0.1188488   1.20535205]
 [-0.87112033  0.11319779  0.42312224  1.47334803]
 [-0.75857622  0.17000839  1.13049576  1.51688198]
 [-0.62665751  0.30333591  1

### 3.5、唯一值与其他集合逻辑

In [16]:
#unique函数。返回一个数组中唯一值排序后形成的数组
names=np.array(['Bob','Joe','Will','Bob','Will','Joe'])
print(np.unique(names))

['Bob' 'Joe' 'Will']


In [17]:
#in1d函数。检查一个数组中的值是否在另一个数组中，返回一个布尔值数组
values=np.array([6,0,0,3,2,5,6])
print(np.in1d(values,[2,3,6]))

[ True False False  True  True False  True]


## 4、用数组输入输出

In [35]:
 #np.save()与np.load()分别用来存和取。默认存储文件后缀为.npy
arr=np.arange(10)
np.save('single_arr',arr)
arr=1
arr1=np.load('single_arr.npy')
print(arr1)

arr2=np.arange(20)
np.savez('some_arr',a=arr,b=arr2)          #np.savez可以指定数组为参数传入函数中，从而在未压缩文件中保存多个数组
arch=np.load('some_arr.npz')               #读取的为字典
print(arch['a'])
print(arch['b'])


'''
从表格中读取数据更多地是利用pandas进行
'''

[0 1 2 3 4 5 6 7 8 9]
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 5、线性代数

In [47]:
#即矩阵间的操作，如点乘、分解等
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
print(x.dot(y),np.dot(x,y),sep='\n')        #
one=np.ones(3)        #此时创建的one数组仅有一个维度，为轴0方向的数组，即为（3*1数组），也即向量，因此可以点乘
print(one,x@one)      #@符号同样为点乘运算符
#因此点乘运算符有array.dot(another_array)\np.dot()\@

[[ 28  64]
 [ 67 181]]
[[ 28  64]
 [ 67 181]]
[1. 1. 1.] [ 6. 15.]


In [2]:
#numpy.linalg包含了许多矩阵分解的函数，另外包括了求逆矩阵、行列式求解等
from numpy.linalg import inv,qr
import numpy as np
x=np.random.randn(5,5)
mat=x.T.dot(x)
print(mat.dot(inv(mat)))  #inv()求逆矩阵

[[ 1.00000000e+00 -1.18883297e-16 -3.54150358e-16 -9.84129462e-17
   1.16970719e-16]
 [-9.77094921e-17  1.00000000e+00 -6.22168958e-17 -3.77575573e-17
  -8.97427382e-17]
 [ 9.13136609e-16 -1.67346152e-16  1.00000000e+00 -1.46016526e-17
  -6.70611595e-16]
 [-2.52239558e-16  1.05404609e-17  1.97619877e-16  1.00000000e+00
  -4.66852179e-16]
 [ 4.74005730e-16  1.07919908e-16  4.53143292e-17  2.37786731e-17
   1.00000000e+00]]


## 6、伪随机数生成

In [3]:
#numpy.random模块提供了随机数生成的方法。Python其实也提供了random方法，但是内建random生成时很慢，远没有numpy.random生成得快
samples=np.random.normal(size=(4,4))   #normal生成一个指定大小得正态分布样本
print(samples)

[[-1.21130057  0.2894207   0.65805451  1.17791558]
 [-0.48196127  1.02931459  1.43019554 -1.21086789]
 [ 0.2700422  -0.61109379 -0.82164568 -2.00841884]
 [ 1.75743145 -0.32540141 -0.06949871 -1.14743399]]


In [6]:
intx=np.random.randint(0,10,size=(4,4))    #randint为整数随机值，产生[0,10)的整数范围
print(intx)

[[7 5 7 7]
 [8 7 2 0]
 [4 1 2 1]
 [7 1 6 7]]


## 7、随机漫步

In [1]:
#模仿随机漫步
import numpy as np
nwalks=50
nsteps=20
draws=np.random.randint(0,2,size=(nwalks,nsteps))   #50次随机漫步，每次20步
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)                   #cumsum()进行累积，内部参数为1，即为沿着轴1进行累积
print(walks)

[[  1   2   1   0  -1   0  -1   0  -1   0   1   0   1   2   1   2   1   0
    1   2]
 [  1   0   1   0   1   2   3   4   5   6   5   6   5   6   5   4   3   4
    3   4]
 [ -1   0   1   0   1   2   1   0   1   2   3   2   1   0  -1  -2  -3  -2
   -1  -2]
 [  1   0  -1  -2  -3  -2  -3  -2  -3  -2  -1   0   1   0  -1  -2  -3  -4
   -3  -2]
 [  1   2   1   0   1   2   3   2   3   2   3   2   1   0  -1   0   1   0
    1   0]
 [  1   0   1   2   3   2   3   2   3   2   3   2   3   2   1   2   1   2
    1   0]
 [  1   0  -1   0   1   0   1   2   3   4   3   4   5   6   5   6   7   8
    7   6]
 [ -1   0   1   0   1   0  -1  -2  -1   0   1   0   1   2   1   0   1   0
   -1   0]
 [  1   0   1   2   3   4   5   4   3   4   3   2   3   2   3   2   3   2
    3   2]
 [ -1   0  -1  -2  -3  -2  -1   0   1   2   3   2   3   2   1   2   3   4
    3   4]
 [  1   0  -1  -2  -1  -2  -1  -2  -3  -4  -3  -2  -1   0   1   2   1   0
    1   2]
 [ -1  -2  -3  -2  -3  -4  -3  -4  -3  -2  -1  -2  -1  -2  -3  -4

In [2]:
hist5=(np.abs(walks)>=5).any(1)
print(hist5)                       #找出有哪一次随机漫步实现了最大漫步距离大于等于5

[False  True False False False False  True False  True False False False
 False  True  True False  True  True False False  True  True  True False
 False  True False  True  True  True  True  True  True  True False  True
  True  True False False  True  True  True False  True False False  True
  True False]


In [3]:
crossing_times=(np.abs(walks[hist5])>=5).argmax(1)           #argmax()可以找出布尔值数组中第一次出现true的位置，其实便是找到数组中第一个最大值的位置
crossing_times1=(np.abs(walks)>=5).argmax(1)
print(crossing_times,'\n\n\n\n',crossing_times1)

[ 8 12  6 10 14 18 12 18  6 14  8 18 18 18  8 12 14 10 16 10  6 16 16 18
 10 10 14] 



 [ 0  8  0  0  0  0 12  0  6  0  0  0  0 10 14  0 18 12  0  0 18  6 14  0
  0  8  0 18 18 18  8 12 14 10  0 16 10  6  0  0 16 16 18  0 10  0  0 10
 14  0]
