# NumPy

## 1、NumPy ndarray：多维数组对象

In [1]:
import numpy as np
data=np.random.randn(2,3)
print(data,data.shape,data.dtype,sep='\n')

#numpy库引入了数组类型，可以方便地进行矩阵运算
#数组内默认数据类型为float64

[[ 2.2538779   1.97717457 -1.45390912]
 [ 1.39385683  0.18391206 -0.55957088]]
(2, 3)
float64


### 1.1生成ndarray

In [15]:
data1=[1,2,3,3.5]
array1=np.array(data1)
data2=[[1,2,3,3.5],[2,3,4,4.5]]
array2=np.array(data2)
print(array1,array2,type(array2),array2.ndim,array2.shape,sep='\n')   #ndarray的nidm方法返回当前数组的维度，shape返回具体的维度大小

arr3=np.empty((2,3,3))   #返回指定大小的未初始化垃圾数据
arr4=np.zeros((3,5))
print('\n',arr3,arr4,sep='\n')

arr5=np.arange(10)       #arange为数组版的range，返回一个数组的序列
print('\n',arr5,sep='\n')

[1.  2.  3.  3.5]
[[1.  2.  3.  3.5]
 [2.  3.  4.  4.5]]
<class 'numpy.ndarray'>
2
(2, 4)


[[[6.23042070e-307 7.56587584e-307 1.37961302e-306]
  [6.23053614e-307 6.23053954e-307 9.34609790e-307]
  [8.45593934e-307 9.34600963e-307 1.86921143e-306]]

 [[6.23061763e-307 8.90104239e-307 6.89804132e-307]
  [1.22387805e-307 1.42418172e-306 8.06610070e-308]
  [6.89810244e-307 1.22387550e-307 2.22522596e-306]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[0 1 2 3 4 5 6 7 8 9]


### 1.2、ndarray的数据类型

In [21]:
arr1=np.array([1.5,2.89,-3.15,4.0],dtype=np.float64)   #直接设定内部的数据类型
print(arr1.dtype)
int_arr1=arr1.astype(np.int64)           #利用astype可以改变数据类型
print(int_arr1.dtype)
print(arr1,int_arr1,sep='\n')           #浮点数转换为整形数之后，小数部分消失

arr2=np.array(['1.25','5.55','6.78'])
float_arr2=arr2.astype(np.float64)     #还可以将具有数字含义的字符串转换为数字
#float_arr2=arr2.astype(arr1.dtype)   同样可以
print(arr2,float_arr2,sep='\n')

float64
int64
[ 1.5   2.89 -3.15  4.  ]
[ 1  2 -3  4]
['1.25' '5.55' '6.78']
[1.25 5.55 6.78]


### 1.3、NumPy数组算术

In [25]:
#任何两个等尺寸数组之间的算术操作都是对应元素的
arr1=np.array([[1,2,3],[2,3,4]])
print(arr1,arr1+arr1,arr1*arr1,1/arr1,arr1**2,sep='\n')
arr2=np.array([[2,3,4],[4,5,6]])
print(arr1>arr2)

[[1 2 3]
 [2 3 4]]
[[2 4 6]
 [4 6 8]]
[[ 1  4  9]
 [ 4  9 16]]
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]]
[[ 1  4  9]
 [ 4  9 16]]
[[False False False]
 [False False False]]


### 1.4、索引与切片

In [41]:
arr1=np.arange(10)
print(arr1)
arr1[5:8]=12
print(arr1)

#比较独特的是数组的切片就是原数组的视图，对切片的修改会传递到原数组上
slice_arr1=arr1[5:8]     #slice_arr1类似指向了arr1的该部分，而不是复制
#copy_arr1=arr1[5:8].copy()   这是复制
slice_arr1[:]=20
print(arr1,slice_arr1)

print('\n')
#与之相对的是列表，自动复制
list1=[2,3,4,5]
list1[1:3]=[12,12]
print(list1)
mp=list1[1:3]
mp=[22,22]
print(list1)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12  8  9]
[ 0  1  2  3  4 20 20 20  8  9] [20 20 20]


[2, 12, 12, 5]
[2, 12, 12, 5]


In [44]:
#多维数组中的索引
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0,2],arr2[0][2],sep='\n')   #两种效果相同
print(arr2[1])

arr3=np.array([[[1,2,3],[4,5,6]],[[2,3,4],[5,6,7]]])
print('\n',arr3[1],arr3[0,1],arr3[0,:1,1:],sep='\n')    #切片时是一步步进行的

3
3
[4 5 6]


[[2 3 4]
 [5 6 7]]
[4 5 6]
[[2 3]]


### 1.5、布尔索引

In [17]:
import numpy as np
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(data,'\n')
print(names=='Bob','\n')
print(data[names=='Bob'],'\n')      #names=='Bob'会产生布尔值数组，因此可以借此作为索引
print(data[names!='Bob'],'\n')
print(data[~(names=='Bob')])

[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  2.06353861]] 

[ True False False  True False False False] 

[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]] 

[[-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  2.06353861]] 

[[-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -

In [21]:
#注意用布尔值索引，产生的不是原本数据的视图，而是拷贝
slice_bool_data=data[names=='Bob']
slice_data=data[[0,3],:]
print(slice_bool_data,slice_data,sep='\n')
slice_bool_data[:,:]=1
print('利用bool索引的数据是拷贝',slice_bool_data,data,sep='\n')
slice_data[:,:]=1
print('利用数组分隔选取的也是拷贝',slice_data,data,sep='\n')


[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]]
[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]]
利用bool索引的数据是拷贝
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  2.06353861]]
利用数组分隔选取的也是拷贝
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.6008719  -0.02714554 -1.21156158 -1.12999837]
 [-0.11001841  3.28875937 -2.59946614 -1.04994963]
 [ 0.59065563  0.11076274 -0.27772756 -0.74356884]
 [-0.78287649  0.82945829 -0.72278757 -0.10127188]
 [-0.50196041  0.9233171   0.311079    0.35140152]
 [ 0.19176876  1.21821396  0.60720216  1.31797562]
 [ 1.32861849 -0.62534267 -0.67450626  

In [22]:
data[data<0]=0  #这个也是布尔值索引
print(data)

[[0.         0.         0.         0.        ]
 [0.         3.28875937 0.         0.        ]
 [0.59065563 0.11076274 0.         0.        ]
 [0.         0.82945829 0.         0.        ]
 [0.         0.9233171  0.311079   0.35140152]
 [0.19176876 1.21821396 0.60720216 1.31797562]
 [1.32861849 0.         0.         2.06353861]]


### 1.6、神奇索引

In [31]:
arr=np.empty((8,4))
for i in range(8):
    arr[i,:]=i
print(arr,end='\n\n')
print(arr[[3,5,4,1],:],'\n',sep='\n')        #神奇索引就是用整数数组进行索引。可以发现，顺序也是可以调换的
print(arr[[-3,-7,-2,-1,0],:],'\n',sep='\n')        #负数就是倒着索引
print(arr[[1,3,5,2],[3,2,0,1]])           #会选取两个数组组合所指向的元素
                                           #会总是将数据复制到一个新数组中

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

[[3. 3. 3. 3.]
 [5. 5. 5. 5.]
 [4. 4. 4. 4.]
 [1. 1. 1. 1.]]


[[5. 5. 5. 5.]
 [1. 1. 1. 1.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]
 [0. 0. 0. 0.]]


[1. 3. 5. 2.]


In [33]:
arr=np.arange(32).reshape((8,4))
print(arr,'\n',arr[[1,5,7,2]][:,[0,3,2,1]],sep='\n')        #arr[[1,5,7,2]]是选中的行，接着选取[:,[0,3,2,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


[[ 4  7  6  5]
 [20 23 22 21]
 [28 31 30 29]
 [ 8 11 10  9]]


### 1.7、数组转置、换轴

In [34]:
#数组的转置
print(arr.T)

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


In [36]:
#矩阵乘
print(np.dot(arr.T,arr))
print(np.dot(arr,arr.T))

[[2240 2352 2464 2576]
 [2352 2472 2592 2712]
 [2464 2592 2720 2848]
 [2576 2712 2848 2984]]
[[  14   38   62   86  110  134  158  182]
 [  38  126  214  302  390  478  566  654]
 [  62  214  366  518  670  822  974 1126]
 [  86  302  518  734  950 1166 1382 1598]
 [ 110  390  670  950 1230 1510 1790 2070]
 [ 134  478  822 1166 1510 1854 2198 2542]
 [ 158  566  974 1382 1790 2198 2606 3014]
 [ 182  654 1126 1598 2070 2542 3014 3486]]


In [47]:
#数组的高维转置
arr=np.arange(16).reshape((2,2,4))
print(arr)
arr_trans=arr.transpose((1,0,2))   #即旧的第二个轴变成了第一个，第一个轴变成了第二个，第三个轴不变，1，0，2分别代表旧数组的第二、一、三个轴
print('.....',arr_trans.shape)
arr_trans=arr.transpose((2,1,0))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((2,0,1))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((1,2,0))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((0,1,2))
print('.....',arr_trans.shape)
arr_trans=arr.transpose((0,2,1))
print('.....',arr_trans.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
..... (2, 2, 4)
..... (4, 2, 2)
..... (4, 2, 2)
..... (2, 4, 2)
..... (2, 2, 4)
..... (2, 4, 2)


In [48]:
#swapaxes方法
arr.swapaxes(1,2)      #接收一对轴编号，对这两个轴进行调换。注意，返回的是视图

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 2、通用函数

In [50]:
#通用函数，称ufunc，是对ndarry数据逐元素操作的函数。

arr=np.arange(16).reshape(2,8)
print(np.sqrt(arr),'\n')
print(np.exp(arr))

[[0.         1.         1.41421356 1.73205081 2.         2.23606798
  2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128
  3.74165739 3.87298335]] 

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
  1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06]]


In [52]:
#modf返回浮点数的小数和整数部分
arr=np.random.randn(7)
remainder,whole_part=np.modf(arr)
print(arr,remainder,whole_part,sep='\n')

[ 2.20828071 -1.67689482 -1.12481404  1.64234093 -0.25654576  1.06180184
  0.78453939]
[ 0.20828071 -0.67689482 -0.12481404  0.64234093 -0.25654576  0.06180184
  0.78453939]
[ 2. -1. -1.  1. -0.  1.  0.]


In [60]:
arr=np.arange(16).reshape(2,8)
arr=arr.astype(np.float64)
arr1=np.sqrt(arr)
print(arr,'\n')
arr2=np.empty((2,8))
arr1=np.sqrt(arr,arr2)
print(arr,arr2,sep='\n')        #ufunc提供一个out参数，可以将计算结果输出到out中

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]] 

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]]
[[0.         1.         1.41421356 1.73205081 2.         2.23606798
  2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128
  3.74165739 3.87298335]]


## 3、面向数组编程